engines:
  eslint:
    enabled: true
    config:
      config: '.eslint.codeclimate.json'
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
   paths:
    - "**.js"
exclude_paths:
  - "test/"
  - "**.json"
